In [0]:
import pandas as pd

In [0]:
dict_1={
    "Nombre":["Ringo","John","Paul","George","Yoko"],
    "Edad":[45,34,42,38,47],
    "Salario":[12000,14000,13000,11000,10000],
    "Genero":["M","M","M","M","F"]
}

In [0]:
df = pd.DataFrame(dict_1)

In [0]:
print ("La diferencia entre el salario más alto ({0}) y el más bajo ({1}) es: {2}".format(df["Salario"].max(), df["Salario"].min(), df["Salario"].max()-df["Salario"].min()))

La diferencia entre el salario más alto (14000) y el más bajo (10000) es: 4000

In [0]:
print("El promedio de salarios es: {0}".format(df["Salario"].mean()))
print("La mediana de salarios es: {0}".format(df["Salario"].median()))
print("La desviación estándar de salarios es: {0}".format(df["Salario"].std()))

El promedio de salarios es: 12000.0
La mediana de salarios es: 12000.0
La desviación estándar de salarios es: 1581.1388300841897